[package]
name = "rreverse"
version = "0.1.0"
authors = ["Grant Miner <xxgsoftware@gmail.com>"]

[dependencies]
kdtree = "~0.2.1"
quick-csv = "0.1.5"
rustc-serialize = "0.3"
time = "*"
iron = "*"
queryst = "1.0.0"
