[package]
name = "rreverse"
version = "0.1.0"
authors = ["Grant Miner <xxgsoftware@gmail.com>"]

[dependencies]
kdtree = "~0.2.1"
csv = "0.14.3"
rustc-serialize = "0.3"
time = "*"
hyper = "0.7"
iron = "*"
