[package]
name = "hyper-reverse-geocoder"
version = "0.1.0"
authors = ["Grant Miner <xxgsoftware@gmail.com>"]

[dependencies]
actix-web = "0.7.8"
geocoder = { path = "../geocoder" }

[[bin]]
name = "actix"
path = "src/actix.rs"
hyper = "0.12.11"
