[package]
name = "rrgeo-warp"
version = "0.1.0"
authors = ["Grant Miner <xxgsoftware@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "^1.4"
reverse_geocoder = { path = "../reverse-geocoder" }
serde = "^1.0"
serde_derive = "^1.0"
time = "0.2.14"
tokio = { version = "0.2", features = ["macros"] }
warp = "0.2.2"

[dev-dependencies]
bytes = "0.5.4"

[[bin]]
name = "rrgeo-warp"
path = "src/warp.rs"
