[package]
name = "reverse_geocoder"
version = "0.1.0"
authors = ["Grant Miner <xxgsoftware@gmail.com>"]

[dependencies]
kdtree = "^0.5"
quick-csv = "^0.1"
rustc-serialize = "^0.3"
time = "^0.1"
serde = "^1.0"
serde_derive = "^1.0"
failure = "^0.1"

[dev-dependencies]
criterion = "0.2"
lazy_static = "^1.3"

[lib]
name = "reverse_geocoder"
path = "src/reverse_geocoder.rs"


[[bench]]
name = "my_benchmark"
harness = false