[package]
name = "reverse_geocoder"
version = "0.1.0"
authors = ["Grant Miner <xxgsoftware@gmail.com>"]
edition = "2018"

[dependencies]
kdtree = "^0.6"
quick-csv = "^0.1"
rustc-serialize = "^0.3"
time = "0.2.1"
serde = "^1.0"
serde_derive = "^1.0"
failure = "^0.1"

[dev-dependencies]
criterion = "0.3"
lazy_static = "^1.4"

[lib]
name = "reverse_geocoder"
path = "src/reverse_geocoder.rs"


[[bench]]
name = "my_benchmark"
harness = false