[package]
name = "reverse-geocoder-cmd"
version = "0.1.0"
authors = ["Grant Miner <xxgsoftware@gmail.com>"]

[dependencies]
reversegeocoder = { path = "../geocoder" }
time = "0.1.40"

[[bin]]
name = "reverse-geocoder-cmd"
path = "src/cmdline.rs"
