[package]
name = "rrgeo-actix"
version = "0.1.0"
authors = ["Grant Miner <xxgsoftware@gmail.com>"]

[dependencies]
actix-web = "1.0.9"
reverse_geocoder = { path = "../reverse-geocoder" }
lazy_static = "^1.4"
time = "0.2.1"
queryst = "^2.0"
serde = "^1.0"
serde_derive = "^1.0"
failure = "^0.1"

[dev-dependencies]
bytes = "0.5.3"

[[bin]]
name = "rrgeo-actix"
path = "src/actix.rs"
