[package]
name = "rrgeo-actix"
version = "0.1.0"
authors = ["Grant Miner <ggcode1@users.noreply.github.com>"]
edition = "2018"

[dependencies]
actix-web = "^3.0.0"
reverse_geocoder = { path = "../reverse-geocoder" }
lazy_static = "^1.4"
time = "^0.2.16"
queryst = "^2.0"
serde = "^1.0"
serde_derive = "^1.0"
env_logger = "^0.8.2"

[dev-dependencies]
bytes = "^1.0.1"
actix-rt = "2.2.0"

[[bin]]
name = "rrgeo-actix"
path = "src/actix.rs"
