[package]
name = "rrgeo-actix"
version = "0.1.0"
authors = ["Grant Miner <xxgsoftware@gmail.com>"]
edition = "2018"

[dependencies]
actix-rt = "1.1.1"
actix-web = "2.0.0"
reverse_geocoder = { path = "../reverse-geocoder" }
lazy_static = "^1.4"
time = "0.2.13"
queryst = "^2.0"
serde = "^1.0"
serde_derive = "^1.0"
failure = "^0.1"
env_logger = "*"

[dev-dependencies]
bytes = "0.5.4"

[[bin]]
name = "rrgeo-actix"
path = "src/actix.rs"
