[package]
name = "iron-reverse-geocoder"
version = "0.1.0"
authors = ["Grant Miner <xxgsoftware@gmail.com>"]

[dependencies]
geocoder = { path = "../geocoder" }

[[bin]]
name = "iron"
path = "src/iron.rs"
